apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-operator
  namespace: flux-system
spec:
  interval: 1m
  path: ../../apps/base/rook-operator/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: rook-ceph