apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ops
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/base/rook-operator
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: rook-ceph
  timeout: 2m0s
  wait: true