apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-cluster-test
  namespace: rook-ceph
spec:
  dependsOn:
    - name: rook-operator
  path: ./cluster-test.yaml
  prune: true
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: homelab
