apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook
  namespace: rook-ceph
spec:
  interval: 1m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: rook
  path: "./cluster"
  prune: true
  timeout: 1m
