machine:
  # Static ip for Talos Linux
  network:
    hostname: "controlplane-{{ control_index }}"
    interfaces:
      - deviceSelector:
          busPath: "0*"
        addresses:
          - "{{ control_ip }}/24"
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.1
        dhcp: false

    nameservers:
      - 192.168.2.1
      - 8.8.4.4
      - 8.8.8.8
      - 1.1.1.1

  # Talos Linux image with system extentions for longhorn
  install:
    image: factory.talos.dev/metal-installer/b1ba84be4f5193a24085cc7e22fce31105e1583504d7d5aef494318f7cb1abd0:v1.10.1

cluster:
  # Privileged access
  apiServer:
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
            enforce: privileged


