machine:
  network:
    hostname: controlplane-1
    interfaces:
      - deviceSelector:
          busPath: "0*"
        addresses:
          - 192.168.2.129/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.1
        dhcp: false

    nameservers:
      - 192.168.2.1
      - 8.8.4.4
      - 8.8.8.8
      - 1.1.1.1
