apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-postgresql
  namespace: n8n-postgresql
spec:
  instances: 1

  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: app-secret

  storage:
    size: 1Gi
