apiVersion: v1
data:
    password: ENC[AES256_GCM,data:FxrK+aV3VlNTs9fMCUbTM1XgfWeZ7cCLFzXUmNc/kTEF1mizpBFHEjXEklTHCNGQngGiSbpGE5bKr/+LpPSyQJRwnFw0WKyvZGQ/L8p9KIdbmdwMVQyRtw==,iv:JI443GVVXLmFHx28ZMptcuzeabbZld31h19pIYnfmvU=,tag:w10BzkV81Z8n39GnM+kOxw==,type:str]
    username: ENC[AES256_GCM,data:ABY6PQ==,iv:XMd4IWfjKwYIHDQCUmFlykL3Xl1jAAWcNwYvSeFjUXU=,tag:VJlQxbq+LyQwVUdOpdh/Kw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: app-secret
sops:
    age:
        - recipient: age1avzxwxmhupw6kavjxh0u3h3s8kxax2dvn4mjzaxw8nl5jyau5csqkveshl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZkJFRnY4ME9wMTdvZlJr
            TWNJMER6WDRvU2hvUGptYytVVlZzT3ljWWcwCkJ1SmJBOFp6QlBHK3FPRUdjd2lB
            NDUzeFlwcDVubmkwYTFYeWlIZ2NFOE0KLS0tIElVbi9wWUpUQ0J5SzBEM0NUc0Nv
            VElUWkxnbFFyYjI5L3hDWmVqK0o1bmcKViQvHZa4+VbKfOBlgpine94FLG5AiLUc
            YaV6oa+3BmuqRhLqk8EzAX7n15V+cDN0UbIL8iU+eBeSbBWcgNGlLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T05:22:03Z"
    mac: ENC[AES256_GCM,data:/p723fn8f1m1MgsyUdxxMlJVEkY0DYKI7njTS9Ul1ADeRVSFFo/EI0Z8G6YTXH//Dk6SFYFp/a2LlEb1FywCjI9+SrLEQVscgd5Q3aUNZyBI6LvflTdEhvZzPvDGvZ2iDmtcu5pQPOzNczB6nFcT3Zzx/+B/sBHQRkBGBrxvJx0=,iv:qKRrzPCZ5HrEHw4tYZToJkoOUM9L/4+G6qs4x+3Fv5Q=,tag:e7hcA+Iw+b4plbkVI3DpBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
