apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: homepage
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homepage
    spec:
      containers:
      - image: php:8.2.27-apache
        name: php
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"

        volumeMounts:
        - mountPath: /var/www/html
          name: homepage-data

        securityContext:
          fsGroup: 33
          runAsUser: 33
          runAsGroup: 33
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false

      initContainers:
      - image: alpine/git:2.47.1
        name: php-init
        command: ["sh", "-c", "mkdir /init && git clone https://github.com/meowosaurus/homepage-homeserver.git /init && cp -r /init/* /var/www/html/"]
        restartPolicy: Always

        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        
        volumeMounts:
        - mountPath: /var/www/html
          name: homepage-data

        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false

      volumes:
      - name: homepage-data
        emptyDir:
          sizeLimit: 500Mi
status: {}
