apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 1m
  chart:
    spec:
      chart: open-webui
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: open-webui
  targetNamespace: open-webui
  values:
    replicaCount: 1