apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 1m
  chart:
    spec:
      chart: open-webui
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: open-webui
  targetNamespace: open-webui
  values:
    replicaCount: 1
    ollama:
      enabled: false
    extraEnvVars:
      - name: OLLAMA_BASE_URL
        value: "http://ollama.ollama.svc.cluster.local:11434"
      - name: OLLAMA_API_BASE_URL
        value: "http://ollama.ollama.svc.cluster.local:11434"
      - name: ENABLE_OLLAMA_API
        value: "True"
      - name: USE_OLLAMA_DOCKER
        value: "false"
      #OLLAMA_API_BASE_URL: "http://ollama.ollama.svc.cluster.local:11434"
      #ENABLE_OLLAMA_API: "True"