apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chartRef:
    kind: HelmChart
    name: open-webui
    namespace: flux-system
  interval: 1m
  values:
    replicaCount: 1