apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falco
      version: "4.21.3"
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: falco
  targetNamespace: falco
  values:
    replicaCount: 1
