apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falcosidekick
  namespace: falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falcosidekick1
      version: "2.31.1"
      sourceRef:
        kind: HelmRepository
        name: falcosidekick
        #namespace: falco
  targetNamespace: falco
  values:
    replicaCount: 1
