apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:dbXi7vswR0YG/Os5,iv:XREexHfw988qOEWOcZqGcI/4Ww++AxNd7ky/C3Ifmso=,tag:LD3EvOWkrvJ1DzBFx5yqoQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:pdTP4XXf5plEjAsURkoAKPaD+1ZsTlGu6lT4qGyjAOlRialVd3JNsEsIBd3+PZCBIAtZBAY/yrTRO60voy/yqGohIuXwspIuRbhr2L3kVRvoi0NA/K3DLYduMQLaReBRn1/RT2ewfqOaOjfcFB1r2iYwBOAf0VW2KYrtWvP6/kGpkLQZ/aJs7cFy3BZDXuDY8OfX9wb2UqNTOXKuYMJtXfy5LMHuAwPxvJP2UA==,iv:j536Dm80HSm9lUo8q3xx0v/OyjcFIleNaiXbWSzEH4g=,tag:KLEslR2m7RuFmSEl1mp3gw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1avzxwxmhupw6kavjxh0u3h3s8kxax2dvn4mjzaxw8nl5jyau5csqkveshl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaFdmZmRLd2tpUlhIOWVL
            c1ArMS9lSTFuQkNacmdOM0x5dktlTmFJbG1FCmtKM0xReVV5MHVSbHVadmxPRERP
            VGJ1dWhNVHRneVlDSlk0Qi9GVURHLzAKLS0tIFFucnB5dmQxUDBwdzZGclFSZnE0
            d21JWHUxc1pkTHdSbmYzK2lhVlczK2MK63C+5ijPRKpOJREe2UIbvnXjql08MZ0n
            92GTNa9RRcYZ8UYgNHD0z2gVplzOBj1aeF/01/5dTGZBbivnm+1exw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T02:41:26Z"
    mac: ENC[AES256_GCM,data:7h/MEqiS+ilUsdgMKMXFeheKcDYBug9bxAsYGreW6Ljt94Wa30oQv2zo6cjyZfwauW/NwiTeeLmFOF3F/3XDJ7KpqXEDpOfg6OpMzlI6BoX4CvuEprmo/b+hgPGCjhdAxcNgMs63OTxtkYjNVp0oGQWcrRHdCxOuoXQcNTWOQXY=,iv:csKrqThc5j7Q1y0Ys5pkefHCZC4/PR6rsheJluTFyF8=,tag:HG2W02OwrcdV1WeZdiai6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
