apiVersion: v1
data:
    password: ENC[AES256_GCM,data:EIwMas8gmvY=,iv:pbHX23TDYuJWZfDoaasVjt2OVEkXFrdxLrP4d33I5R8=,tag:nmWGXSqlEGTwL+z0EUh3gw==,type:str]
    user: ENC[AES256_GCM,data:B5Zz8UoK8co=,iv:eK77UjTVVIoWUzG/Ua7Jo1be6h7Ut60yngSXGNoaK10=,tag:Gb7w2/DHRxn+x3xKKdH34g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1avzxwxmhupw6kavjxh0u3h3s8kxax2dvn4mjzaxw8nl5jyau5csqkveshl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNzV4endwTzNHK3JLMGFj
            ZUV5MzJJNlRQQlNKWk43dGxPUks2MWc0dVRNClA4eWE4akpSTnRETXB2ZWxLY2lX
            c3BreGpUWDU4ZDd2am1sM0pvYkRsWlEKLS0tIE5yanNiN2RQcWRNME8zNjB4UkIw
            OTlLK3B0dzBTS2hsVGd3akJxYzJNNDQK1ntuKMmbuTurTdOSjiVAJ7LGcEca9X3l
            JgdLukWeYUN6o08Iu11tD42oPvhp1BFJg05atsa3enTgdB/qAchNaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T23:27:20Z"
    mac: ENC[AES256_GCM,data:RMCi2WzlmDBrvGvdE3CXgwsGfZbau852gTTWd70QvY4qdvOW3O8Bms/X771w+e7lRHgeX1aKkDKA9CF2fwtYDqTJf9KcLC8BMBub0uffM2zWRkVdcgawwkt4GJ9aAfRwf0VZ2LMGpZIXiMa2Oev0TcBE1lxF39sC8A/quRq4BMA=,iv:7swzp1fuowzZ6oJmj04/JQEA8qV3Kkc9DQ0cmx7LRSI=,tag:epFZD2B9SuBMdTppLEXV+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.9.2
