apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 1m0s
  retryInterval: 1m
  timeout: 5m
  sourceRef: 
    kind: GitRepository
    name: cnpg-system
  path: ./databases/cnpg-system
  prune: true