apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-base
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 1m
  timeout: 5m
  sourceRef: 
    kind: GitRepository
    name: flux-system
  path: ./storage/base
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
spec:
  dependsOn:
    - name: storage-base
  interval: 5m
  path: ./storage/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: storage