apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falcosidekick
      version: "2.31.1"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: falcosecurity
  targetNamespace: falcosecurity
  values:
    replicaCount: 1
