apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql-deploy
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-deploy
    spec:
      containers:
      - image: mysql
        name: mysql
        resources: {}

        envFrom:
        - secretRef:
            name: mysql-container-env

        volumeMonuts:
        - mountPath: /var/lib/mysql
          name: mysql-app-volume
      volumes:
      - name: mysql-app-volume
        persistentVolumeClaim:
          claimName: mysql-app-pvc
status: {}
