apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nextcloud-deploy
  name: nextcloud-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nextcloud-deploy
    spec:
      containers:
      - image: nextcloud
        name: nextcloud
        resources: {}
status: {}
