apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nextcloud-deploy
  name: nextcloud-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nextcloud-deploy
    spec:
      containers:
      - image: nextcloud
        name: nextcloud
        resources: {}

        envFrom:
        - secretRef:
            name: nextcloud-container-env

        volumeMounts:
          - mountPath: /var/www/html/
            name: nextcloud-app-volume
      volumes:
      - name: nextcloud-app-volume
        persistantVolumeClaim:
          claimName: nextcloud-app-pvc
status: {}
