apiVersion: v1
data:
    MYSQL_DATABASE: ENC[AES256_GCM,data:bkqSwxks2dYEF3eT,iv:ZUdpojNJ254ebYRsq2NzpSvLQvfuAoYFVNnr45SXYCM=,tag:ZR8g/mEehuwtwfsEjhvPEA==,type:str]
    MYSQL_HOST: ENC[AES256_GCM,data:Z4ndzOiANj4hwl+xRxkgin7bb3Q=,iv:RtsqiLnSUn++ubE+c6QDwsQEx9lCFe6Lo5USAZ6g4F4=,tag:sqa0oBIJxA/YLuAxojPmVw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:acQIqaUlj5fwqtP6Ayl1pWmil1GY9/nZAf6Ykq5tNLZ1tDT7x67uFiKyaeQWsxKrBvTwkwmz4ZkYyBPxa/Qu2it++j5KBu60iOz1xmS8dMVes9RGYAqToGdyxjm9ZzvhLSkRZibNhaHuRnrmDKkgycLkWJ0jRbhceoTXZWOI/EmkLPGgdMODvcP/05Pg8DZ3x/I+mVY8v/4weMdjdNf+FZSmM25t/KA6k1r2xA==,iv:gx8iQoS/XIwVf2A8zHvgfhfTa2NhnCSXolcTyY/QuP0=,tag:Smy/ONun/4TfiCiCpb9/aQ==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:KhBzJnyzhuqOno4Q,iv:9ALJT8xU7w0McTvir+5No913GK5eO/KsJ+97QW6WAFk=,tag:TH2O9Mi9NqUWAxckVg+pmw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nextcloud-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1avzxwxmhupw6kavjxh0u3h3s8kxax2dvn4mjzaxw8nl5jyau5csqkveshl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TjUrT2ZHUmJCaVhpeEJ0
            SHNNc2JrSkoyUnh3ZnhzVVVnWmtkWTJkdkFZCkhxNWIzT1NPUjV6K2p3RExaSTI4
            SVdJMnloUEpGZklzV0ord21QRGlSMEkKLS0tIHN0aU50TkV0MXBwaytVRkZDRnlT
            QzREOVRzYUQ2emFkYmw2N3pTaEsyZGMK59CFYjrNzZBhG0aKkHhrMAEKhvV9m8Wr
            0QtPff/5+AnsqRISUN4rxB6ZpOhyrmlRUZKk0eAqe3e2Y0/jN/gjfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T01:14:15Z"
    mac: ENC[AES256_GCM,data:qZsW/8ZjkJKh4Ph6jnig9QK0TR8SHbbCXh/Yapj5jomoE27/4NDlW+8Yl4vIPoOg69P5P2MWIwYF5A0dmViqoss+fDdfXnpEm9vWgNwmDHlaGyA9kU0ynyzjxFICG0OD/OYpyVnpKq1UkXaSevnVsEVko3VhScLRVqwwwNv/1OM=,iv:rr2mQ0FfUXv4G3IkQOCuYJ2syuN1m2zoxrvlNPFZJEE=,tag:uAQ2Af0xWK5t8yBxQNHvvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
