# Source: nextcloud/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
    labels:
        app.kubernetes.io/name: nextcloud
        helm.sh/chart: nextcloud-6.5.2
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/managed-by: Helm
type: Opaque
data:
    nextcloud-username: ENC[AES256_GCM,data:R2dM203QV7I=,iv:TZ4wdexYnJRgZCGiS9r9WfV+3kSr2wRbL3tOGeNN6pc=,tag:XOqU//kWCOc2srUWCz8piA==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:5fb2vFira84=,iv:KOw5TPgRJmaMC6gWfjZUrqVtY5Pzfg3GEbjsHoXTzik=,tag:De/QFg9AuSRa5nX3CvhJVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1avzxwxmhupw6kavjxh0u3h3s8kxax2dvn4mjzaxw8nl5jyau5csqkveshl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieDNmdTNGWGpXWndLMVFK
            bUtJVDZFOTNOckdPOFRkTlhLSFdKdVlBM1hrCm1wMFFZR2YvamFnd2ZEcDR3R0lK
            ZEY5SVZYT2VRTWhTMUxpRlUzaFRWK0UKLS0tIG9NbCt4M0YrMHFKMFMrS0xhUnZs
            dThRVHFOL09GcjRNcVhvNFQ5bGV4VzQKB2CL4mBZYFhMXQv251o+sNBsQtno0FVb
            eftbmRGW45hUmC7fBBtOg8W870GazQsyV9dnRnI0n82ydYcUafntKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-29T06:16:06Z"
    mac: ENC[AES256_GCM,data:IafLk3bLD0w7A9Heq7nbLJISLK593fWQPcpRKAyG7RBYVOKbPOZQKTTHnaDgo9F44G3DyjZOgJUe8v0X5doN3SFBbYuj5lgI9Mja4+VVJn2RA3f1QuSUjHk0usDAoBThzxVAfga790efkwDui2uFNlmEfoOr5i4lk6/qKydunk4=,iv:tci+S1zY8HTY1uj0KUfJbTT+KZ5HFqRvdBfKGHVIEwQ=,tag:Jr+djmiC81n+rn5d199z3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
