apiVersion: v1
data:
    db-password: ENC[AES256_GCM,data:RoWBJiW0o3QkjfZrn0TkAoJXcC4cLin4pOY9LRYxKUdRS6pRwn3mU5jpzNFOC6t01gC1UOwp79nxpwuAFL15XDBmXmUm9NQqhFfLzxmxYyCSxdBNhugL0A==,iv:Kfg515pxb3B1rHyHdzQtpeuNCsL3TPjSZZaKI2QV9ZM=,tag:qRDxlEeTtw+EItDPdybApg==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:A0BW9SCfnZpQAyaMmpM5VByJHPKBYJ52aJUSLrf6rwZLjN9e75jVEeXGz9a0rUe71C5oCTJiHjY5FzuJ/YV/z909q6DJKAZ0JK73Sjl+muaWQoGXUeM2QZZ4L3SJ1FYGSUS96OrSbNnigLszsYkFamnZ5z5rnYpc+98LyxiRkH3ypKElJfspfmUzqL7WIYgrPRlDRnRBsLqglMb15LNbMIVf21yFaXFnqVzIdg==,iv:92+c5m5+/6exLpw1m48pbcype/4z7/iwgEZGWJmizxw=,tag:IHsoMcIl+QV4lWYFnE157g==,type:str]
    nextcloud-username: ENC[AES256_GCM,data:XmJebNOMJzZExOfX,iv:mqz3lLsPzpE3LlClFK0LoZvWpWrWGKzftW3YlTvH8/8=,tag:9ao1kH16BpMHBp6cPnMQWg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nextcloud-secrets
sops:
    age:
        - recipient: age1avzxwxmhupw6kavjxh0u3h3s8kxax2dvn4mjzaxw8nl5jyau5csqkveshl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcmgyaVNJQmZ0N2h3S1BM
            cHVLNXpNZ0VnQ1ZjeVc1S2Z3dHhNUU1ObmdBCkdpQXh0VFBWVU1XS1NPRTRqaFZD
            NTZpY2Vpc2Y0S2lPSW5sVS9iekZweVEKLS0tIDVHbWZiVVlLRnJieVBsWUNFRFl2
            UUR5WkhkTXdKR2xDSm9aNHpwbGZzRmsKOGi8R1Pv0ewdG4gIovo1LqmeA2WqU3YQ
            NH7izk5mvPV/Z3XjvWVzcIJMygVUgxwjhzj+sAF6fvishH7+5bxfuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T04:34:57Z"
    mac: ENC[AES256_GCM,data:B8Ser9lsYdX8w9xryoGHS9mIPwUFE4kx8H6BztbNZXWJpsmtAPFRsqCiusXSt70C65i4xDOtHTH2Gjj4rmigqvAXsm3Q7rhGcqtV+SD7VECQ+lLKoVuXgxePTHBUgjmtRSS0taRJRUX8BhENIkPrAxsjHFziOv5MXr/BgSIgiIE=,iv:nif2ew0k1Nm9EkCz4K06wPqxTEnOuSwI0+QgtU4Mb0E=,tag:WWyfwgaGzuwWCOdLs+f/oA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
