apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: n8n
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: n8n
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /home/node/.n8n"]
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
      containers:
      - image: n8nio/n8n:latest
        name: n8n

        env:
        - name: DB_TYPE
          value: "postgresdb"
        - name: DB_POSTGRESDB_DATABASE
          value: "n8n"
        - name: DB_POSTGRESDB_HOST
          value: "n8n-postgresql-rw.n8n-postgresql.svc.cluster.local"
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        - name: DB_POSTGRESDB_USER
          value: "n8n"
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: database-password
status: {}
