apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: homepage
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homepage
    spec:
      containers:
      - image: php:8.2.27-apache
        name: php
        resources: {}

        volumeMounts:
        - mountPath: /var/www/html
          name: homepage-data

        securityContext:
          fsGroup: 33
          runAsUser: 33
          runAsGroup: 33
          allowPrivilegeEscalation: false

      initContainers:
      - image: alpine/git:2.47.1
        name: php-init
        command: ["sh", "-c", "mkdir /init-data2 && git clone https://github.com/meowosaurus/homepage-homeserver.git /init-data2 && cp -r /init-data2/* /var/www/html/"]
        restartPolicy: Always
        
        volumeMounts:
        - mountPath: /var/www/html
          name: homepage-data

        securityContext:
          allowPrivilegeEscalation: false

      volumes:
      - name: homepage-data
        emptyDir:
          sizeLimit: 500Mi
status: {}
