apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: homepage
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homepage
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33

      containers:
      - image: php:8.2.27-apache
        name: php
        resources: {}

        volumeMounts:
        - mountPath: /var/www/html
          name: homepage-data

        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: homepage-data
        persistentVolumeClaim:
          claimName: homepage-data-pvc
status: {}
