apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: homepage
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homepage
    spec:
      containers:
      - image: ghcr.io/gethomepage/homepage:v1.0.4
        name: homepage
        resources: {}

        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"

        volumeMounts:
        - mountPath: /app/config
          name: homepage-config

        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      
      volumes:
      - name: homepage-config
        persistentVolumeClaim:
          claimName: homepage-config-pvc
status: {}
