---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate-1
  namespace: flux-system
spec:
  chart:
    spec:
      chart: twingate/connector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: twingate
  interval: 1m0s
