---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate-1
  namespace: twingate
spec:
  chart:
    spec:
      chart: twingate/connector
      reconcileStrategy: ChartVersion
      sourceRef:
        name: ""
  interval: 1m0s
