apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud-postgresql
spec:
  instances: 3

  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: app-secret

  storage:
    size: 1Gi
