apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud-postgresql
resources:
  - ../../base/nextcloud-db/
  #- deployment.yaml
  #- namespace.yaml
  - secret.yaml

patchesStrategicMerge:
  - deployment_overwrite.yaml
