apiVersion: v1
kind: Service
metadata:
  labels:
    app: podinfo
  name: podinfo
  namespace: podinfo
spec:
  ports:
  - name: 5678-9898
    port: 5678
    protocol: TCP
    targetPort: 9898
  selector:
    app: podinfo
  type: ClusterIP
status:
  loadBalancer: {}
