apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:lts
        name: mysql
        
        envFrom:
        - secretRef:
            name: mysql-env

        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false

        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits: 
            cpu: "2"
            memory: "2Gi"

        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
status: {}
