apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: linkding
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33

      containers:
      - image: sissbruecker/linkding:1.31.0
        name: linkding

        envFrom:
          - secretRef:
              name: linkding-container-env

        resources:
          limits:
            cpu: "1"
            memory: "1Gi"

        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false

        volumeMounts:
        - mountPath: /etc/linkding/data
          name: linkding-data
      volumes:
      - name: linkding-data
        persistentVolumeClaim:
          claimName: linkding-data-pvc
status: {}
