apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: linkding
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linkding
    spec:
      containers:
      - image: sissbruecker/linkding:1.31.0
        name: linkding
        resources: {}
        #volumeMounts:
        #- mountPath: /etc/linkding/data
        #  name: linkding-data
    volumes:
    - name: linkding-data
      persistentVolumeClaim:
        claimName: linkding-data-pvc
status: {}
