apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: linkding-lb
  name: linkding-lb
spec:
  ports:
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: linkding-lb
  type: LoadBalancer
status:
  loadBalancer: {}
