name: Kubernetes CI Tests
run-name: Kubernetes CI Tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.bashrc
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - name: Install dependencies
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gcc
          sudo apt install build-essential
      - name: Install packages
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt update
          brew install kube-linter
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check Kubernetes Manifests
        run: | 
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          kube-linter lint ${{ github.workspace }}
          
      
